name: id_logging
description: Logging implementations for cleanarch projects.
version: 1.1.0
license: MIT
repository: https://github.com/staylorx/id_logging
issue_tracker: https://github.com/staylorx/id_logging/issues
documentation: https://github.com/staylorx/id_logging

environment:
  sdk: ^3.10.0

dependencies:
  logger: ^2.0.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
